#tomcat pot
server:
  port: 9003
 
#jsp
spring:
  mvc:
    view:
      prefix: /WEB-INF/market/
      suffix: .jsp
      
  devtools:
    livereload:
      enabled: true
      
#mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/sist?serverTimezone=Asia/Seoul
    username: root
    password: 1234